#!/bin/sh
#
# This shell script will be placed in /etc/apcupsd
# Sends a message to your discord webhook
# Requires a string parameter to be passed in ($1)
#

# Supply your personal discord bot webhook
discordwebhookurl="YOUR_DISCORD_WEBHOOK_HERE"

curl -H "Content-Type: application/json" -X POST -d '{"content":"'"${1}"'"}' $discordwebhookurl
exit 0