#!/bin/sh
#
# This shell script if placed in /etc/apcupsd
# will be called by /etc/apcupsd/apccontrol when apcupsd
# restores contact with the UPS (i.e. the serial connection is restored).
# We send an email message to root to notify him.
#

# Create custom message
HOSTNAME=`hostname`
MSG="Communication with UPS has been restored 📞: 🟢"

# Get clean looking status from UPS and add it to our message
status="`/bin/bash /etc/apcupsd/common-getcleanstatus`"

# Send discord notification with message
/bin/bash /etc/apcupsd/common-notifydiscord "$MSG"
/bin/bash /etc/apcupsd/common-notifydiscord "\`\`\`$status\`\`\`"

# Email code included with apcupsd
# (
#    echo "$MSG"
#    echo " "
#    /sbin/apcaccess status
# ) | $APCUPSD_MAIL -s "$MSG" $SYSADMIN
exit 0