#!/bin/sh
#
# This shell script if placed in /etc/apcupsd
# will be called by /etc/apcupsd/apccontrol when the UPS
# goes on batteries.
# We send an email message to root to notify him.
#
# Create custom message
HOSTNAME=`hostname`
MSG="Main power has been lost! System should be switching to battery backup."

# Send discord notification with message
/bin/bash /etc/apcupsd/common-notifydiscord "$MSG"

# Email code included with apcupsd
# (
#    echo "$MSG"
#    echo " "
#    /sbin/apcaccess status
# ) | $APCUPSD_MAIL -s "$MSG" $SYSADMIN
exit 0